attributes_dict = {
    1: 'has a curved bill',
    2: 'has a dagger bill',
    3: 'has a hooked bill',
    4: 'has a needle bill',
    5: 'has a hooked seabird bill',
    6: 'has a spatulate bill',
    7: 'has a all purpose bill',
    8: 'has a cone bill',
    9: 'has a specialized bill',
    10: 'has blue wings',
    11: 'has brown wings',
    12: 'has iridescent wings',
    13: 'has purple wings',
    14: 'has rufous wings',
    15: 'has grey wings',
    16: 'has yellow wings',
    17: 'has olive wings',
    18: 'has green wings',
    19: 'has pink wings',
    20: 'has orange wings',
    21: 'has black wings',
    22: 'has white wings',
    23: 'has red wings',
    24: 'has buff wings',
    25: 'has blue upperparts',
    26: 'has brown upperparts',
    27: 'has iridescent upperparts',
    28: 'has purple upperparts',
    29: 'has rufous upperparts',
    30: 'has grey upperparts',
    31: 'has yellow upperparts',
    32: 'has olive upperparts',
    33: 'has green upperparts',
    34: 'has pink upperparts',
    35: 'has orange upperparts',
    36: 'has black upperparts',
    37: 'has white upperparts',
    38: 'has red upperparts',
    39: 'has buff upperparts',
    40: 'has blue underparts',
    41: 'has brown underparts',
    42: 'has iridescent underparts',
    43: 'has purple underparts',
    44: 'has rufous underparts',
    45: 'has grey underparts',
    46: 'has yellow underparts',
    47: 'has olive underparts',
    48: 'has green underparts',
    49: 'has pink underparts',
    50: 'has orange underparts',
    51: 'has black underparts',
    52: 'has white underparts',
    53: 'has red underparts',
    54: 'has buff underparts',
    55: 'has solid breast pattern',
    56: 'has spotted breast pattern',
    57: 'has striped breast pattern',
    58: 'has multicolored breast pattern',
    59: 'has a blue back',
    60: 'has a brown back',
    61: 'has a iridescent back',
    62: 'has a purple back',
    63: 'has a rufous back',
    64: 'has a grey back',
    65: 'has a yellow back',
    66: 'has a olive back',
    67: 'has a green back',
    68: 'has a pink back',
    69: 'has a orange back',
    70: 'has a black back',
    71: 'has a white back',
    72: 'has a red back',
    73: 'has a buff back',
    74: 'has a forked tail',
    75: 'has a rounded tail',
    76: 'has a notched tail',
    77: 'has a fan shaped tail',
    78: 'has a pointed tail',
    79: 'has a squared tail',
    80: 'has a blue upper tail',
    81: 'has a brown upper tail',
    82: 'has a iridescent upper tail',
    83: 'has a purple upper tail',
    84: 'has a rufous upper tail',
    85: 'has a grey upper tail',
    86: 'has a yellow upper tail',
    87: 'has a olive upper tail',
    88: 'has a green upper tail',
    89: 'has a pink upper tail',
    90: 'has a orange upper tail',
    91: 'has a black upper tail',
    92: 'has a white upper tail',
    93: 'has a red upper tail',
    94: 'has a buff upper tail',
    95: 'has a spotted head',
    96: 'has a malar head',
    97: 'has a crested head',
    98: 'has a masked head',
    99: 'has a unique head',
    100: 'has a eyebrow head',
    101: 'has a eyering head',
    102: 'has a plain head',
    103: 'has a eyeline head',
    104: 'has a striped head',
    105: 'has a capped head',
    106: 'has a blue breast',
    107: 'has a brown breast',
    108: 'has a iridescent breast',
    109: 'has a purple breast',
    110: 'has a rufous breast',
    111: 'has a grey breast',
    112: 'has a yellow breast',
    113: 'has a olive breast',
    114: 'has a green breast',
    115: 'has a pink breast',
    116: 'has a orange breast',
    117: 'has a black breast',
    118: 'has a white breast',
    119: 'has a red breast',
    120: 'has a buff breast',
    121: 'has a blue throat',
    122: 'has a brown throat',
    123: 'has a iridescent throat',
    124: 'has a purple throat',
    125: 'has a rufous throat',
    126: 'has a grey throat',
    127: 'has a yellow throat',
    128: 'has a olive throat',
    129: 'has a green throat',
    130: 'has a pink throat',
    131: 'has a orange throat',
    132: 'has a black throat',
    133: 'has a white throat',
    134: 'has a red throat',
    135: 'has a buff throat',
    136: 'has blue eyes',
    137: 'has brown eyes',
    138: 'has purple eyes',
    139: 'has rufous eyes',
    140: 'has grey eyes',
    141: 'has yellow eyes',
    142: 'has olive eyes',
    143: 'has green eyes',
    144: 'has pink eyes',
    145: 'has orange eyes',
    146: 'has black eyes',
    147: 'has white eyes',
    148: 'has red eyes',
    149: 'has buff eyes',
    150: 'has same length bill as head',
    151: 'has a long bill',
    152: 'has a short bill',
    153: 'has a blue forehead',
    154: 'has a brown forehead',
    155: 'has a iridescent forehead',
    156: 'has a purple forehead',
    157: 'has a rufous forehead',
    158: 'has a grey forehead',
    159: 'has a yellow forehead',
    160: 'has a olive forehead',
    161: 'has a green forehead',
    162: 'has a pink forehead',
    163: 'has a orange forehead',
    164: 'has a black forehead',
    165: 'has a white forehead',
    166: 'has a red forehead',
    167: 'has a buff forehead',
    168: 'has a blue under tail',
    169: 'has a brown under tail',
    170: 'has a iridescent under tail',
    171: 'has a purple under tail',
    172: 'has a rufous under tail',
    173: 'has a grey under tail',
    174: 'has a yellow under tail',
    175: 'has a olive under tail',
    176: 'has a green under tail',
    177: 'has a pink under tail',
    178: 'has a orange under tail',
    179: 'has a black under tail',
    180: 'has a white under tail',
    181: 'has a red under tail',
    182: 'has a buff under tail',
    183: 'has a blue nape',
    184: 'has a brown nape',
    185: 'has a iridescent nape',
    186: 'has a purple nape',
    187: 'has a rufous nape',
    188: 'has a grey nape',
    189: 'has a yellow nape',
    190: 'has a olive nape',
    191: 'has a green nape',
    192: 'has a pink nape',
    193: 'has a orange nape',
    194: 'has a black nape',
    195: 'has a white nape',
    196: 'has a red nape',
    197: 'has a buff nape',
    198: 'has a blue belly',
    199: 'has a brown belly',
    200: 'has a iridescent belly',
    201: 'has a purple belly',
    202: 'has a rufous belly',
    203: 'has a grey belly',
    204: 'has a yellow belly',
    205: 'has a olive belly',
    206: 'has a green belly',
    207: 'has a pink belly',
    208: 'has a orange belly',
    209: 'has a black belly',
    210: 'has a white belly',
    211: 'has a red belly',
    212: 'has a buff belly',
    213: 'has rounded wings',
    214: 'has pointed wings',
    215: 'has broad wings',
    216: 'has tapered wings',
    217: 'has long wings',
    218: 'is large',
    219: 'is small',
    220: 'is very large',
    221: 'is medium',
    222: 'is very small',
    223: 'is shaped like upright perching water',
    224: 'is shaped like chicken',
    225: 'is shaped like long legged',
    226: 'is shaped like duck',
    227: 'is shaped like owl',
    228: 'is shaped like gull',
    229: 'is shaped like hummingbird',
    230: 'is shaped like pigeon',
    231: 'is shaped like tree clinging',
    232: 'is shaped like hawk',
    233: 'is shaped like sandpiper',
    234: 'is shaped like upland ground',
    235: 'is shaped like swallow',
    236: 'is shaped like perching',
    237: 'has solid back',
    238: 'has spotted back',
    239: 'has striped back',
    240: 'has multi colored back',
    241: 'has solid tail',
    242: 'has spotted tail',
    243: 'has striped tail',
    244: 'has multi colored tail',
    245: 'has solid belly',
    246: 'has spotted belly',
    247: 'has striped belly',
    248: 'has multi colored belly',
    249: 'has blue primary color',
    250: 'has brown primary color',
    251: 'has iridescent primary color',
    252: 'has purple primary color',
    253: 'has rufous primary color',
    254: 'has grey primary color',
    255: 'has yellow primary color',
    256: 'has olive primary color',
    257: 'has green primary color',
    258: 'has pink primary color',
    259: 'has orange primary color',
    260: 'has black primary color',
    261: 'has white primary color',
    262: 'has red primary color',
    263: 'has buff primary color',
    264: 'has blue legs',
    265: 'has brown legs',
    266: 'has iridescent legs',
    267: 'has purple legs',
    268: 'has rufous legs',
    269: 'has grey legs',
    270: 'has yellow legs',
    271: 'has olive legs',
    272: 'has green legs',
    273: 'has pink legs',
    274: 'has orange legs',
    275: 'has black legs',
    276: 'has white legs',
    277: 'has red legs',
    278: 'has buff legs',
    279: 'has blue bills',
    280: 'has brown bills',
    281: 'has iridescent bills',
    282: 'has purple bills',
    283: 'has rufous bills',
    284: 'has grey bills',
    285: 'has yellow bills',
    286: 'has olive bills',
    287: 'has green bills',
    288: 'has pink bills',
    289: 'has orange bills',
    290: 'has black bills',
    291: 'has white bills',
    292: 'has red bills',
    293: 'has buff bills',
    294: 'has a blue crown',
    295: 'has a brown crown',
    296: 'has a iridescent crown',
    297: 'has a purple crown',
    298: 'has a rufous crown',
    299: 'has a grey crown',
    300: 'has a yellow crown',
    301: 'has a olive crown',
    302: 'has a green crown',
    303: 'has a pink crown',
    304: 'has a orange crown',
    305: 'has a black crown',
    306: 'has a white crown',
    307: 'has a red crown',
    308: 'has a buff crown',
    309: 'has a solid wing pattern',
    310: 'has a spotted wing pattern',
    311: 'has a striped wing pattern',
    312: 'has a multi colored wing pattern',
}